---
title: "Automatic_CaSTLe_Classification of Control3"
author: "Lisa"
date: "5/20/2021"
output: html_document
---

# source activate TransLearnTest

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Directions

```{r dirs}
dir <- "/data/bioinf/projects/data/2019_schROHT/2021_CaSTLeAnnot/"
input <- paste0(dir,"input/")
rdata <- paste0(dir,"RData/")
results <- paste0(dir,"results/")
```

# Packages & Parameters

```{r packages}
set.seed(123)

library(SingleCellExperiment)
library(xtable)
library(scater)  # tested on version 1.6.3,    install from Bioconductor: source("https://bioconductor.org/biocLite.R"); biocLite("scater")
library(xgboost) # tested on version 0.6.4.1, install from CRAN: install.packages("xgboost")
library(igraph)  # tested on version 1.2.1,   install from CRAN: install.packages("igraph")
BREAKS=c(-1, 0, 1, 6, Inf)
nFeatures = 100

```
```{r funtions}

run_CaSTLe <- function(source_data, target_data, data_type){
  source = readRDS(source_data)
target = readRDS(target_data)
sourceCellTypes = colData(source)[,"X"]
#--------------------------------------------------------------------------

source_n_cells_counts = apply(exprs(source), 1, function(x) { sum(x > 0) } )
target_n_cells_counts = apply(exprs(target), 1, function(x) { sum(x > 0) } )
common_genes = intersect( rownames(source)[source_n_cells_counts>10], 
                          rownames(target)[target_n_cells_counts>10]
)
remove(source_n_cells_counts, target_n_cells_counts)
#--------------------------------------------------------------------------
ds1 = t(exprs(source)) 
ds1 = ds1[, colnames(ds1) %in% common_genes]
ds2 = t(exprs(target)) 
remove(source, target)

ds2 = ds2[, colnames(ds2) %in% common_genes]
ds = rbind(ds1[,common_genes], ds2[,common_genes])
isSource = c(rep(TRUE,nrow(ds1)), rep(FALSE,nrow(ds2)))
remove(ds1, ds2)
#--------------------------------------------------------------------------
# 3. Highest mean in both source and target
topFeaturesAvg = colnames(ds)[order(apply(ds, 2, mean), decreasing = T)]

# 4. Highest mutual information in source
topFeaturesMi = names(sort(apply(ds[isSource,],2,function(x) { compare(cut(x,breaks=BREAKS),sourceCellTypes,method = "nmi") }), decreasing = T))

# 5. Top n genes that appear in both mi and avg
selectedFeatures = union(head(topFeaturesAvg, nFeatures) , head(topFeaturesMi, nFeatures) )

# 6. remove correlated features
tmp = cor(ds[,selectedFeatures], method = "pearson")
tmp[!lower.tri(tmp)] = 0
selectedFeatures = selectedFeatures[apply(tmp,2,function(x) any(x < 0.9))]
remove(tmp)
#--------------------------------------------------------------------------

# 7,8. Convert data from continous to binned dummy vars
# break datasets to bins
dsBins = apply(ds[, selectedFeatures], 2, cut, breaks= BREAKS)
# use only bins with more than one value
nUniq = apply(dsBins, 2, function(x) { length(unique(x)) })
# convert to dummy vars
ds = model.matrix(~ . , as.data.frame(dsBins[,nUniq>1]))
remove(dsBins, nUniq)

# 9. Classify
train = runif(nrow(ds[isSource,]))<0.8
# slightly different setup for multiclass and binary classification
if (length(unique(sourceCellTypes)) > 2) {
  xg=xgboost(data=ds[isSource,][train, ] , 
       label=as.numeric(sourceCellTypes[train])-1,
       objective="multi:softmax", num_class=length(unique(sourceCellTypes)),
       eta=0.7 , nthread=5, nround=20, verbose=0,
       gamma=0.001, max_depth=5, min_child_weight=10)
} else {
  xg=xgboost(data=ds[isSource,][train, ] , 
       label=as.numeric(sourceCellTypes[train])-1,
       eta=0.7 , nthread=5, nround=20, verbose=0,
       gamma=0.001, max_depth=5, min_child_weight=10)
}

save(xg, file =paste0(rdata,"CaSTLe_XGBoost_Control3_run_",data_type,".RData") )

#--------------------------------------------------------------------------
cat("Quantities includes in training data: ")
print(xtable(table(sourceCellTypes[train])))

cat("------------------------------------------------------------------------------------")

cat("Quantities includes in test data: ")
print(xtable(table(sourceCellTypes[!train])))
cat("------------------------------------------------------------------------------------")



eval_df <- data.frame(true_labels = c(as.numeric(sourceCellTypes[!train])-1),
                      pred_labels = c(predict(xg, ds[isSource, ][!train, ])))
save(eval_df, file = paste0(rdata,"CaSTLe_Eval_DF_Control3_run_",data_type,".RData"))


# 10. Predict
predictedClasses = predict(xg, ds[!isSource, ])

save(predictedClasses, file = paste0(rdata,"CaSTLe_Annot_output_Control3_",data_type,".RData"))
rm(predictedClasses,xg)
}

```




```{r run_fovea}

run_CaSTLe(source_data = paste0(rdata,"01_Roska_RefData_Foveal_adult.rds"), 
           target_data = paste0(rdata,"01_HRO_Control3_TestData.rds"), 
           data_type= "Foveal_adult")

```

```{r run_organoid}

run_CaSTLe(source_data = paste0(rdata,"01_Roska_RefData.rds"), 
           target_data = paste0(rdata,"01_HRO_Control3_TestData.rds"), 
           data_type= "Organoid")

```

```{r run_peri}

run_CaSTLe(source_data = paste0(rdata,"01_Roska_RefData_Foveal_adult.rds"), 
           target_data = paste0(rdata,"01_HRO_Control3_TestData.rds"), 
           data_type= "Peri_adult")

```

```{r}
sessionInfo()

```
